### ISSUE TITLE
Scripture Table expects a string, but gets an object

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/scripture-resources-rcl#21]
This manifests as a warning. This was introduced by changes to make license information available. Here is the warning from the console:
```
index.js:1 Warning: Failed prop type: Invalid prop `titles[0]` of type `object` supplied to `ScriptureTable`, expected `string`.
    in ScriptureTable (created by ParallelScripture)
    in ParallelScripture (created by Component)
    in Component (created by FunctionComponentWrapper)
    in ResourcesContextProvider (created by FunctionComponentWrapper)
    in FunctionComponentWrapper (created by StateHolder)
    in StateHolder (created by ReactExample)
    in Wrapper (created by ReactExample)
    in ReactExample
```
Prior to this change, Scripture Table was passed a string array of titles. Now, it is getting an array of React MUI components. Here is the code:
```js
          _title = (
            <Typography variant='caption'>
              {title} v{version}{rightsIcon}
            </Typography>
          )
```

It is a warning and the code seems to work OK, but it does imply that the design for Scripture Table needs to be tweaked as it was not intended to work this way. Perhaps another property (optional) could be added that will add the License component if needed. At present, this "addition" is being made in the parent [ParallelScripture].

**Comment by klappy** [comment]
This is not QA testable.
