### ISSUE TITLE
Alert Message -when repo does not exist in the Organizational workflow

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/scripture-resources-rcl#22]

**Comment by klappy** [comment]
Testable in `1.0.0-beta.2`

**Comment by birchamp** [comment]
@RoyalSix is there any way to not leave the organization page and still show the alert?  Do we need to go into the Resources page?

**Comment by elsylambert** [comment]
Seems to be good for now. The issue tcc- #154 written up for enhancement.
