### ISSUE TITLE
Bugfix: missing styling properties from License component

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/scripture-resources-rcl#24]
The following is missing from `ParallelScripture`:
```
 style={{fontSize: "1em", marginLeft: "0.1em"}}
```

**Comment by klappy** [comment]
Testable via `1.0.0-beta.1`

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.0.0-beta.2.

**Comment by BincyJ** [comment]
Since bug fix.think this should be closed and does not need to be demoed. Let me know if otherwise.
