### ISSUE TITLE
Unhighlighting in scripture pane on click no longer works

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/scripture-resources-rcl#29]
once a word is highlighted in the scripture resources it can't be unhighlighted

**Comment by mandolyte** [comment]
@birchamp is this still a problem on beta.5? Whenever I remove a word from the OrigQuote, it unhighlights as expected. If it still is happening, can you provide more details so that I can replicate?
@RoyalSix

**Comment by ancientTexts-net** [comment]
Testable in `ScriptureResourcesRcl v1.0.0-rc.7`

https://scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

**Comment by elsylambert** [comment]
Verified in ScriptureResourcesRcl v1.0.0-rc.7. Highlight and unhighlight works fine in the RCL. However, this has to be verified on the tc create app.

@ancientTexts-net Highlight with ellipsis fails. When you add the ellipsis and an original word to the Original Quote, the highlight goes away. 
[Highlights with ellipsis.mp4.zip](https://github.com/unfoldingWord/scripture-resources-rcl/files/4826759/Highlights.with.ellipsis.mp4.zip)

**Comment by ancientTexts-net** [comment]
@elsylambert -- highlight will ellipsis requires the ellipsis character (…) and a `occurrence` >= 0

I believe the tests for selections do not allow highlighting for `occurrence` === `-1`

Can we please chat?  or is this correct, please?

**Comment by ancientTexts-net** [comment]
@RoyalSix  ^^

**Comment by ancientTexts-net** [comment]
@elsylambert , @RoyalSix  -- EDIT: i was wrong about ellipsis character -- sorry!

but I believe `occurrence` > `0` is required

is this correct please?

**Comment by elsylambert** [comment]
@ancientTexts-net yes works fine with Occurrence as 1.
