### ISSUE TITLE
Prevent delay on early fast scrolling

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/scripture-resources-rcl#33]
[ ] Add 'Spinner' for fetching the scripture resource - Add Lazy load/suspense 
[ ] In order to do parallel parsing, add a parsing state so if the first one starts the parsing then the others wait. 

DoD: Immediate fast scrolling doesn't lock up app AND while the parsing happens the spinner is displayed.

**Comment by RoyalSix** [comment]
@ancientTexts-net 
Are you able to test the following link and let me know if this issue has been resolved and I can make the correct PR's. Thank you!
https://5f36a25d93ef59fd86f8a148--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
@RoyalSix -- wow, Jay! This helps performance so much!

I wish the spinner was centered.  The spinner is more obvious now.

**Comment by mandolyte** [comment]
@RoyalSix I thought I'd try the link above and selected UTN for Ruth. I had the infinite spinner problem; so this code doesn't have the fix for that. I guess the code is going against production, which I don't have access to... any way to make it go to QA?

**Comment by RoyalSix** [comment]
Hey @mandolyte This is the build using the bg server and also @ancientTexts-net I made an update to the spinner location 
https://5f3c00a93c017ff95210177d--tc-create-app.netlify.app/

**Comment by mandolyte** [comment]
Yes, huge difference! I'd love to know what you did!


Cecil
