### ISSUE TITLE
Parallel Scripture: occurrence -1 not rendering as expected.

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/scripture-resources-rcl#47]
Modifying the Quote doesn't appear to render any highlights when occurrence -1 is used.
It should highlight all occurrences of a word/phrase.

Via the demo: https://scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

**Comment by birchamp** [comment]
related issue tcc#94

**Comment by elsylambert** [comment]
![Screen Shot 2020-10-20 at 2.15.23 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b5ff7fa0-6496-4576-b0d5-9b937871d2fd)

**Comment by elsylambert** [comment]
![Screen Shot 2020-10-20 at 2.17.21 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7e54386f-1f89-4f9a-83c3-1d2f7bcdd34e)

**Comment by ancientTexts-net** [comment]
Talked to Jay
fixed in latest version of

markdown-translatable
datatable-translatable

**Comment by RoyalSix** [comment]
Confirmed issues working [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/):
 - `Hightlight is not showing up when text is pasted from OL to original Quote:`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.0.5-rc.7. -1 Occurrence number highlights all occurrence of a word in Scripture pane.
